CREATE TABLE import_jobs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    job_uid VARCHAR(64) NOT NULL,
    import_type VARCHAR(64) NOT NULL,
    input_path TEXT NULL,
    input_url TEXT NULL,
    raw_sources_root TEXT NULL,
    recursive_scan TINYINT(1) NOT NULL DEFAULT 1,
    organize_mode VARCHAR(64) NOT NULL DEFAULT 'copy',
    max_copy_file_size_mb INT NOT NULL DEFAULT 100,
    source_platform VARCHAR(128) NULL,
    connector_name VARCHAR(128) NULL,
    connector_status VARCHAR(64) NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    total_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    skipped_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_import_jobs_job_uid (job_uid),
    KEY idx_import_jobs_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_files (
    id BIGINT NOT NULL AUTO_INCREMENT,
    file_uid VARCHAR(64) NOT NULL,
    import_job_id BIGINT NOT NULL,
    file_name VARCHAR(512) NOT NULL,
    file_ext VARCHAR(32) NULL,
    original_path TEXT NOT NULL,
    managed_path TEXT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    mime_type VARCHAR(128) NULL,
    content_hash VARCHAR(128) NULL,
    parser_name VARCHAR(128) NULL,
    parse_status VARCHAR(64) NOT NULL DEFAULT 'pending',
    organize_status VARCHAR(64) NOT NULL DEFAULT 'pending',
    duplicate_of_file_id BIGINT NULL,
    parse_error TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_files_file_uid (file_uid),
    KEY idx_source_files_job (import_job_id),
    KEY idx_source_files_hash (content_hash),
    CONSTRAINT fk_source_files_import_job FOREIGN KEY (import_job_id) REFERENCES import_jobs(id),
    CONSTRAINT fk_source_files_duplicate FOREIGN KEY (duplicate_of_file_id) REFERENCES source_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
