CREATE TABLE obsidian_notes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    note_uid VARCHAR(64) NOT NULL,
    source_id BIGINT NOT NULL,
    source_file_id BIGINT NULL,
    note_type VARCHAR(64) NOT NULL DEFAULT 'source_note',
    vault_name VARCHAR(128) NOT NULL,
    vault_path VARCHAR(1024) NOT NULL,
    absolute_path VARCHAR(2048) NOT NULL,
    obsidian_uri VARCHAR(2048) NOT NULL,
    title VARCHAR(512) NOT NULL,
    frontmatter_json JSON NULL,
    content_hash VARCHAR(128) NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'written',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_obsidian_notes_note_uid (note_uid),
    KEY idx_obsidian_notes_source_id (source_id),
    KEY idx_obsidian_notes_source_file_id (source_file_id),
    KEY idx_obsidian_notes_vault_path (vault_path(255)),
    CONSTRAINT fk_obsidian_notes_source FOREIGN KEY (source_id) REFERENCES sources(id),
    CONSTRAINT fk_obsidian_notes_source_file FOREIGN KEY (source_file_id) REFERENCES source_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
