CREATE TABLE vector_export_jobs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    export_uid VARCHAR(64) NOT NULL,
    scope VARCHAR(64) NOT NULL,
    target_collection VARCHAR(128) NOT NULL,
    export_format VARCHAR(32) NOT NULL DEFAULT 'jsonl',
    status VARCHAR(64) NOT NULL DEFAULT 'completed',
    total_count INT NOT NULL DEFAULT 0,
    export_file_name VARCHAR(255) NULL,
    export_relative_path VARCHAR(1024) NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_vector_export_jobs_export_uid (export_uid),
    KEY idx_vector_export_jobs_status_created (status, created_at),
    KEY idx_vector_export_jobs_scope_created (scope, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE content_chunks (
    id BIGINT NOT NULL AUTO_INCREMENT,
    chunk_uid VARCHAR(64) NOT NULL,
    export_uid VARCHAR(64) NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    source_uid VARCHAR(64) NULL,
    file_uid VARCHAR(64) NULL,
    record_uid VARCHAR(64) NULL,
    title VARCHAR(512) NULL,
    chunk_index INT NOT NULL DEFAULT 0,
    chunk_text LONGTEXT NOT NULL,
    text_hash VARCHAR(128) NOT NULL,
    char_count INT NOT NULL DEFAULT 0,
    token_estimate INT NOT NULL DEFAULT 0,
    metadata_json JSON NULL,
    embedding_status VARCHAR(64) NOT NULL DEFAULT 'pending',
    target_collection VARCHAR(128) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_content_chunks_chunk_uid (chunk_uid),
    KEY idx_content_chunks_export_uid (export_uid),
    KEY idx_content_chunks_content_type (content_type),
    KEY idx_content_chunks_embedding_status (embedding_status),
    KEY idx_content_chunks_target_collection (target_collection)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
