CREATE TABLE mcp_tool_calls (
    id BIGINT NOT NULL AUTO_INCREMENT,
    call_uid VARCHAR(64) NOT NULL,
    tool_name VARCHAR(128) NOT NULL,
    caller_type VARCHAR(64) NOT NULL,
    caller_id VARCHAR(128) NOT NULL,
    input_json JSON NULL,
    output_json JSON NULL,
    status VARCHAR(64) NOT NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_mcp_tool_calls_call_uid (call_uid),
    KEY idx_mcp_tool_calls_tool_created (tool_name, created_at),
    KEY idx_mcp_tool_calls_status_created (status, created_at),
    KEY idx_mcp_tool_calls_caller_created (caller_type, caller_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE personal_records (
    id BIGINT NOT NULL AUTO_INCREMENT,
    record_uid VARCHAR(64) NOT NULL,
    record_type VARCHAR(64) NOT NULL,
    title VARCHAR(512) NOT NULL,
    occurred_at DATETIME NULL,
    source_channel VARCHAR(128) NOT NULL DEFAULT 'mcp',
    source_ref TEXT NULL,
    raw_content LONGTEXT NOT NULL,
    structured_json JSON NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    sensitivity_level VARCHAR(32) NOT NULL DEFAULT 'medium',
    created_by VARCHAR(128) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_personal_records_record_uid (record_uid),
    KEY idx_personal_records_type_created (record_type, created_at),
    KEY idx_personal_records_status_created (status, created_at),
    KEY idx_personal_records_channel_created (source_channel, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
