CREATE TABLE knowledge_maintenance_runs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_uid VARCHAR(64) NOT NULL,
    run_type VARCHAR(64) NOT NULL DEFAULT 'manual',
    status VARCHAR(64) NOT NULL DEFAULT 'completed',
    stale_days INT NOT NULL DEFAULT 7,
    total_count INT NOT NULL DEFAULT 0,
    issue_count INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_maintenance_runs_run_uid (run_uid),
    KEY idx_maintenance_runs_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE knowledge_maintenance_items (
    id BIGINT NOT NULL AUTO_INCREMENT,
    item_uid VARCHAR(64) NOT NULL,
    run_uid VARCHAR(64) NOT NULL,
    issue_type VARCHAR(64) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    content_type VARCHAR(64) NOT NULL,
    source_uid VARCHAR(64) NULL,
    file_uid VARCHAR(64) NULL,
    record_uid VARCHAR(64) NULL,
    chunk_uid VARCHAR(64) NULL,
    export_uid VARCHAR(64) NULL,
    title VARCHAR(512) NULL,
    summary TEXT NOT NULL,
    evidence_json JSON NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'open',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_maintenance_items_item_uid (item_uid),
    KEY idx_maintenance_items_run_uid (run_uid),
    KEY idx_maintenance_items_issue_type (issue_type),
    KEY idx_maintenance_items_status_created (status, created_at),
    KEY idx_maintenance_items_content_refs (source_uid, file_uid, record_uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
