CREATE TABLE agent_runs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    run_uid VARCHAR(64) NOT NULL,
    source_id BIGINT NOT NULL,
    source_file_id BIGINT NULL,
    run_type VARCHAR(64) NOT NULL,
    pipeline_version VARCHAR(64) NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    current_step VARCHAR(64) NULL,
    model_provider VARCHAR(128) NULL,
    model_name VARCHAR(128) NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    final_decision VARCHAR(64) NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_runs_run_uid (run_uid),
    KEY idx_agent_runs_source (source_id),
    KEY idx_agent_runs_status_created (status, created_at),
    CONSTRAINT fk_agent_runs_source FOREIGN KEY (source_id) REFERENCES sources(id),
    CONSTRAINT fk_agent_runs_source_file FOREIGN KEY (source_file_id) REFERENCES source_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE agent_steps (
    id BIGINT NOT NULL AUTO_INCREMENT,
    step_uid VARCHAR(64) NOT NULL,
    run_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    source_file_id BIGINT NULL,
    step_name VARCHAR(64) NOT NULL,
    agent_name VARCHAR(128) NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    input_json JSON NULL,
    output_json JSON NULL,
    model_provider VARCHAR(128) NULL,
    model_name VARCHAR(128) NULL,
    prompt_version VARCHAR(64) NULL,
    error_message TEXT NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_steps_step_uid (step_uid),
    KEY idx_agent_steps_run (run_id),
    KEY idx_agent_steps_source (source_id),
    CONSTRAINT fk_agent_steps_run FOREIGN KEY (run_id) REFERENCES agent_runs(id),
    CONSTRAINT fk_agent_steps_source FOREIGN KEY (source_id) REFERENCES sources(id),
    CONSTRAINT fk_agent_steps_source_file FOREIGN KEY (source_file_id) REFERENCES source_files(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE review_items (
    id BIGINT NOT NULL AUTO_INCREMENT,
    review_uid VARCHAR(64) NOT NULL,
    source_id BIGINT NOT NULL,
    source_file_id BIGINT NULL,
    run_id BIGINT NOT NULL,
    review_type VARCHAR(64) NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    reason TEXT NULL,
    suggested_changes_json JSON NULL,
    markdown_draft LONGTEXT NULL,
    user_decision TEXT NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_review_items_review_uid (review_uid),
    KEY idx_review_items_status_created (status, created_at),
    KEY idx_review_items_source (source_id),
    KEY idx_review_items_run (run_id),
    CONSTRAINT fk_review_items_source FOREIGN KEY (source_id) REFERENCES sources(id),
    CONSTRAINT fk_review_items_source_file FOREIGN KEY (source_file_id) REFERENCES source_files(id),
    CONSTRAINT fk_review_items_run FOREIGN KEY (run_id) REFERENCES agent_runs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
